### ISSUE TITLE
Updates tracker

### ISSUE THREAD

**Issue by dysfunc** [sveltestrap/sveltestrap#1]
## Updates

**Package**
- [x] Update package.json to use type `module`
- [x] Support Node 20.x with 18.x as min version
- [x] Add DEVELOPER.md
- [x] Add CONTRIBUTING.md
- [x] Add COC.md (Code of Conduct)

**Development**
- [x] Upgrade `Svelte 3.x` to `4.x`
- [x] Replace `Rollup` with `Vite`
- [x] Replace `Jest` with `Vitest`
- [x] Replace `npm` with `pnpm` 
- [x] Update `TSConfig` config
- [x] Update `Prettier` config
- [x] Update `ESLint` config
- [x] Update to `Storybook 7.6.5`
- [x] Add `precommit` hooks for development using `Husky` + `lintstaged`

**CI/CD**
- [x] Add new GitHub actions
  - [x] Storybook (UI Components)
  - [x] Unit tests (Vitest)
  - [x] Publish (NPM)
  - [x] Release tagging (GitHub)
  - [x] Integration tests (Cypress)
    - [x] Standalone
    - [x] SvelteKit
    - [x] Sapper
  
**Source**
- [x] Update exports and test patterns
- [x] Modularize components (component, test, story, type def, snapshot, etc.)
- [x] Add snapshots to tests
- [x] Update TypeScript definitions
- [x] Migrate stories to new format
  - [x] Accordion
  - [x] Alert
  - [x] Badge
  - [x] Breadcrumb
  - [x] Button
  - [x] Card
  - [x] Carousel
  - [x] Container
  - [x] Dropdown
  - [x] Fade
  - [x] FormGroup
  - [x] Grid
  - [x] Icon
  - [x] Image
  - [x] Input
  - [x] InputGroup
  - [x] ListGroup
  - [x] Modal
  - [x] Nav
  - [x] Navbar
  - [x] Offcanvas
  - [x] Pagination
  - [x] Popover
  - [x] Progress
  - [x] Spinner
  - [x] Styles
  - [x] Table
  - [x] Tabs
  - [x] Toast
  - [x] Tooltip
  - [x] Validation

## Resolves

**Pull requests**
- https://github.com/bestguy/sveltestrap/pull/418
- https://github.com/bestguy/sveltestrap/pull/459
- https://github.com/bestguy/sveltestrap/pull/491
- https://github.com/bestguy/sveltestrap/pull/531
- https://github.com/bestguy/sveltestrap/pull/534
- https://github.com/bestguy/sveltestrap/pull/574
- https://github.com/bestguy/sveltestrap/pull/575

**Issues**
- https://github.com/bestguy/sveltestrap/issues/515
- https://github.com/bestguy/sveltestrap/issues/557
- https://github.com/bestguy/sveltestrap/issues/561
- https://github.com/bestguy/sveltestrap/issues/568
- https://github.com/bestguy/sveltestrap/issues/579
